# Portland Trail Blazers - Feature Selection Experiment
* StellarAlgo Data Science
* Ryan Kazmerik & Nakisa Rad
* October 8, 2021

## Hypothesis
Write about the hunch you have and why you're running this experiment.

## Experiment
Document the experiment including selecting data, data transformations, feature engineering and modelling

In [2]:
import getpass
import pyodbc
import pandas as pd
import warnings

from pycaret.classification import *

warnings.filterwarnings('ignore')

### Connecting to MSSQL to get our dataset:

In [3]:
SERVER = '52.44.171.130' 
DATABASE = 'datascience' 
USERNAME = 'dsAdminWrite' 
PASSWORD = getpass.getpass(prompt='Enter your password')
CNXN = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER='+SERVER+';DATABASE='+DATABASE+';UID='+USERNAME+';PWD='+ PASSWORD)

Enter your password········

In [9]:
lkupclientid = 5 # Portland Trail Blazers

cursor = CNXN.cursor()

storedProc = (
    f"""Exec [stlrTrailBlazers].[ds].[getRetentionScoringModelData] {lkupclientid}"""
)

df = pd.read_sql(storedProc, CNXN)

CNXN.commit()
cursor.close()

df.head()

,lkupClientId,dimCustomerMasterId,customerNumber,year,productGrouping,totalSpent,recentDate,attendancePercent,renewedBeforeDays,isBuyer,source_tenure,tenure,distToVenue,totalGames,recency,missed_games_1,missed_games_2,missed_games_over_2,click_link,fill_out_form,open_email,send_email,unsubscribe_email,openToSendRatio,clickToSendRatio,clickToOpenRatio,posting_records,resale_records,resale_atp,forward_records,cancel_records,email,inbound_email,inbound_phonecall,inperson_contact,internal_note,left_message,outbound_email,outbound_phonecall,phonecall,text,unknown,gender,childrenPresentInHH,maritalStatus,lengthOfResidenceInYrs,annualHHIncome,education,urbanicity,isnextyear_buyer,isnextyear_samepkg_buyer,pkgupgrade_status,auto_renewal,credits_after_refund,isNextYear_Buyer
0,5,291872257,200052974,2017,Full Season,7416.64,1970-01-01,0.0,232,TRUE,422,422,28.11,0,0,0,0,1,48,0,118,340,0,0.347059,0.141176,0.406780,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,Unknown,1,1,10.0,74999,High School,None,None,None,None,None,0.0,1
1,5,291872701,201245348,2017,Partial Season,820.00,1970-01-01,0.0,51,TRUE,155,155,8.84,0,0,0,1,0,36,4,46,78,4,0.589744,0.461538,0.782609,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,Unknown,1,1,10.0,74999,High School,None,None,None,None,None,0.0,1
2,5,291873913,862442,2017,Full Season,9108.00,1970-01-01,0.0,239,TRUE,429,429,12.71,0,0,0,0,1,20,0,92,330,0,0.278788,0.060606,0.217391,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,Female,1,1,15.0,74999,High School,None,None,None,None,None,0.0,1
3,5,291873952,203980106,2017,Partial Season,212.00,1970-01-01,0.0,18,TRUE,150,150,22.89,0,0,0,1,0,0,0,0,28,0,0.000000,0.000000,0.000000,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,Male,1,1,11.0,74999,High School,None,None,None,None,None,0.0,0
4,5,291875399,170639,2017,Full Season,19008.00,1970-01-01,0.0,232,TRUE,422,422,156.30,0,0,0,0,1,272,2,328,552,0,0.594203,0.492754,0.829268,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,Unknown,1,1,10.0,74999,High School,None,None,None,None,None,0.0,1

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18489 entries, 0 to 18488
Data columns (total 55 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   lkupClientId              18489 non-null  int64
 1   dimCustomerMasterId       18489 non-null  int64
 2   customerNumber            18489 non-null  object
 3   year                      18489 non-null  object
 4   productGrouping           18489 non-null  object
 5   totalSpent                18489 non-null  float64
 6   recentDate                18489 non-null  object
 7   attendancePercent         18489 non-null  float64
 8   renewedBeforeDays         18489 non-null  int64
 9   isBuyer                   18489 non-null  object
 10  source_tenure             18489 non-null  int64
 11  tenure                    18489 non-null  int64
 12  distToVenue               18489 non-null  float64
 13  totalGames                18489 non-null  int64
 14  recency                   18489 non-null  int64
 15  missed_games_1            18489 non-null  int64
 16  missed_games_2            18489 non-null  int64
 17  missed_games_over_2       18489 non-null  int64
 18  click_link                18489 non-null  int64
 19  fill_out_form             18489 non-null  int64
 20  open_email                18489 non-null  int64
 21  send_email                18489 non-null  int64
 22  unsubscribe_email         18489 non-null  int64
 23  openToSendRatio           18489 non-null  float64
 24  clickToSendRatio          18489 non-null  float64
 25  clickToOpenRatio          18489 non-null  float64
 26  posting_records           18489 non-null  int64
 27  resale_records            18489 non-null  int64
 28  resale_atp                18489 non-null  float64
 29  forward_records           18489 non-null  int64
 30  cancel_records            18489 non-null  int64
 31  email                     18489 non-null  int64
 32  inbound_email             18489 non-null  int64
 33  inbound_phonecall         18489 non-null  int64
 34  inperson_contact          18489 non-null  int64
 35  internal_note             18489 non-null  int64
 36  left_message              18489 non-null  int64
 37  outbound_email            18489 non-null  int64
 38  outbound_phonecall        18489 non-null  int64
 39  phonecall                 18489 non-null  int64
 40  text                      18489 non-null  int64
 41  unknown                   18489 non-null  int64
 42  gender                    18489 non-null  object
 43  childrenPresentInHH       18489 non-null  int64
 44  maritalStatus             18489 non-null  int64
 45  lengthOfResidenceInYrs    18489 non-null  float64
 46  annualHHIncome            18489 non-null  object
 47  education                 18489 non-null  object
 48  urbanicity                0 non-null      object
 49  isnextyear_buyer          0 non-null      object
 50  isnextyear_samepkg_buyer  0 non-null      object
 51  pkgupgrade_status         0 non-null      object
 52  auto_renewal              0 non-null      object
 53  credits_after_refund      18489 non-null  float64
 54  isNextYear_Buyer          18489 non-null  int64
dtypes: float64(9), int64(33), object(13)
memory usage: 7.8+ MB

In [ ]:
df_train_A = df.sample(frac=0.9, random_state=786)
df_train_B = df.sample(frac=0.9, random_state=786)

df_eval = df.drop(df_train.index)

print('Data for Modeling: ' + str(df_train.shape))
print('Unseen Data For Predictions: ' + str(df_eval.shape))

## Results
Show the results of your experiment, don't try to explain them, just show the metrics

## Observations
Here you can document some ideas on the results from above

## Conclusions
Here you can talk about next steps, did the experiment work? If yes, what to do next? If no, why?