In [3]:
import getpass
import pyodbc
import pandas as pd
import warnings

warnings.filterwarnings('ignore')

In [4]:
# connect to SQL Server.
SERVER = '52.44.171.130' 
DATABASE = 'datascience' 
USERNAME = 'dsAdminWrite' 
PASSWORD = getpass.getpass(prompt='Enter your password')
CNXN = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER='+SERVER+';DATABASE='+DATABASE+';UID='+USERNAME+';PWD='+ PASSWORD)

Enter your password ····················

In [3]:
lkupclientid = 36 # flames

cursor = CNXN.cursor()

storedProc = (
    f"""Exec [stlrFlames].[ds].[getRetentionScoringModelData] {lkupclientid}"""
)

df = pd.read_sql(storedProc, CNXN)

CNXN.commit()
cursor.close()

df.shape

(38816, 54)

In [1]:
df.to_parquet('df_flames.parquet.gzip', compression='gzip')  
df_from_parquet = pd.read_parquet('df_flames.parquet.gzip')

NameError: name 'df' is not defined

In [5]:
df_from_parquet.shape

(38816, 54)

In [6]:
df_from_parquet.head()

,lkupClientId,dimCustomerMasterId,customerNumber,year,productGrouping,totalSpent,recentDate,attendancePercent,renewedBeforeDays,isBuyer,source_tenure,tenure,distToVenue,totalGames,recency,missed_games_1,missed_games_2,missed_games_over_2,click_link,fill_out_form,open_email,send_email,unsubscribe_email,openToSendRatio,clickToSendRatio,clickToOpenRatio,posting_records,resale_records,resale_atp,forward_records,cancel_records,email,inbound_email,inbound_phonecall,inperson_contact,internal_note,left_message,outbound_email,outbound_phonecall,phonecall,text,unknown,gender,childrenPresentInHH,maritalStatus,lengthOfResidenceInYrs,annualHHIncome,education,urbanicity,credits_after_refund,is_Lockdown,NumberofGamesPerSeason,CNTPostponedGames,isNextYear_Buyer
0,36,216,263210,2015,Full Season,10919.96,2016-04-07,0.950000,252.0,TRUE,6570,435.0,7.03,41,0,5,1,1,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,Unknown,1,1,None,None,None,None,0.00,0,41,0,1
1,36,405,145233,2015,Full Season,31779.56,2016-04-07,1.006250,252.0,TRUE,14235,435.0,25.44,41,0,2,0,0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,Unknown,1,1,None,None,None,None,0.00,0,41,0,1
2,36,414,134805,2015,Full Season,18233.84,2016-04-07,1.025000,252.0,TRUE,13505,435.0,8.39,41,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,Unknown,1,1,None,None,None,None,0.00,0,41,0,1
3,36,428,172197,2015,Full Season,2173.36,2016-04-07,0.925000,252.0,TRUE,7300,435.0,13.23,37,0,2,1,0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,Unknown,1,1,None,None,None,None,799.20,0,41,0,1
4,36,458,144991,2015,Full Season,39304.60,2016-04-07,0.978125,252.0,TRUE,9855,435.0,25.44,41,0,5,1,0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,Unknown,1,1,None,None,None,None,22646.44,0,41,0,0

In [7]:
df_from_parquet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38816 entries, 0 to 38815
Data columns (total 54 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   lkupClientId            38816 non-null  int64
 1   dimCustomerMasterId     38816 non-null  int64
 2   customerNumber          38816 non-null  object
 3   year                    38816 non-null  object
 4   productGrouping         38816 non-null  object
 5   totalSpent              38816 non-null  float64
 6   recentDate              38816 non-null  object
 7   attendancePercent       38816 non-null  float64
 8   renewedBeforeDays       38815 non-null  float64
 9   isBuyer                 38816 non-null  object
 10  source_tenure           38816 non-null  int64
 11  tenure                  38815 non-null  float64
 12  distToVenue             38816 non-null  float64
 13  totalGames              38816 non-null  int64
 14  recency                 38816 non-null  int64
 15  missed_games_1          38816 non-null  int64
 16  missed_games_2          38816 non-null  int64
 17  missed_games_over_2     38816 non-null  int64
 18  click_link              38816 non-null  int64
 19  fill_out_form           38816 non-null  int64
 20  open_email              38816 non-null  int64
 21  send_email              38816 non-null  int64
 22  unsubscribe_email       38816 non-null  int64
 23  openToSendRatio         38816 non-null  float64
 24  clickToSendRatio        38816 non-null  float64
 25  clickToOpenRatio        38816 non-null  float64
 26  posting_records         38816 non-null  int64
 27  resale_records          38816 non-null  int64
 28  resale_atp              38816 non-null  float64
 29  forward_records         38816 non-null  int64
 30  cancel_records          38816 non-null  int64
 31  email                   38816 non-null  int64
 32  inbound_email           38816 non-null  int64
 33  inbound_phonecall       38816 non-null  int64
 34  inperson_contact        38816 non-null  int64
 35  internal_note           38816 non-null  int64
 36  left_message            38816 non-null  int64
 37  outbound_email          38816 non-null  int64
 38  outbound_phonecall      38816 non-null  int64
 39  phonecall               38816 non-null  int64
 40  text                    38816 non-null  int64
 41  unknown                 38816 non-null  int64
 42  gender                  38816 non-null  object
 43  childrenPresentInHH     38816 non-null  int64
 44  maritalStatus           38816 non-null  int64
 45  lengthOfResidenceInYrs  0 non-null      object
 46  annualHHIncome          0 non-null      object
 47  education               0 non-null      object
 48  urbanicity              0 non-null      object
 49  credits_after_refund    38816 non-null  float64
 50  is_Lockdown             38816 non-null  int64
 51  NumberofGamesPerSeason  38816 non-null  int64
 52  CNTPostponedGames       38816 non-null  int64
 53  isNextYear_Buyer        38816 non-null  int64
dtypes: float64(10), int64(34), object(10)
memory usage: 16.0+ MB